apiVersion: batch/v1
kind: Job
metadata:
 name: my-sql-dump
spec:
 ttlSecondsAfterFinished: 0
 template:
   metadata:
     name: my-sql-dump
   spec:
     containers:
     - name: my-sql-seed
       image: jlsrly/mysql-git
       command:
         - 'bash'
         - '-c'
         - |
           git clone https://github.com/DeekshithSN/kubernetes.git
           mysql -h mysql -u root -padmin -e 'CREATE DATABASE IF NOT EXISTS test';
           mysql -h mysql -u root -padmin test < kubernetes/datadump/mysql.sql
           sleep 36
     restartPolicy: OnFailure
